# Generated by Django 3.0.8 on 2020-07-27 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shift_logs', '0002_auto_20200726_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftlog',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shift_logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
