# Generated by Django 3.0.8 on 2020-07-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_logs', '0003_shiftlog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftlog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shiftlog',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
